// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BaseResponse struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}

type CaptchaResponse struct {
	CaptchaId string `json:"captcha_id"`
	ImgBase64 string `json:"img_base64"`
}

type ChangePasswordRequest struct {
	Email           string `json:"email"`
	EmailVerifyCode string `json:"email_verify_code"`
	New             string `json:"new"`
}

type ChatRequest struct {
	Prompt string `json:"prompt"`
	Model  string `json:"model"`
	Stream bool   `json:"stream"`
}

type ChatResponse struct {
	Success  bool   `json:"success"`
	Response string `json:"response"`
	Done     bool   `json:"done"`
}

type GetUserInfoResponse struct {
	Username         string `json:"username"`
	Nickname         string `json:"nickname"`
	WalletAddr       string `json:"wallet_addr"`
	UserReferralCode string `json:"user_referral_code"`
	ReferralCode     string `json:"referral_code"`
}

type LoginRequest struct {
	Username    string `json:"username"`
	Password    string `json:"password"`
	CaptchaId   string `json:"captcha_id"`
	CaptchaCode string `json:"captcha_code"`
}

type LoginResponse struct {
	Token            string `json:"token"`
	UserId           int64  `json:"user_id"`
	Username         string `json:"username"`
	Nickname         string `json:"nickname"`
	Email            string `json:"email"`
	WalletAddr       string `json:"wallet_addr"`
	UserReferralCode string `json:"user_referral_code"`
	ReferralCode     string `json:"referral_code"`
}

type RegistRequest struct {
	Username        string `json:"username" validate:"required,min=3,max=12"`
	Password        string `json:"password" validate:"required,min=6"`
	Nickname        string `json:"nickname" validate:"max=16"`
	Email           string `json:"email"`
	EmailVerifyCode string `json:"email_verify_code"`
	WalletAddr      string `json:"wallet_addr"`
	ReferralCode    string `json:"referral_code"`
	CaptchaId       string `json:"captcha_id"`
	CaptchaCode     string `json:"captcha_code"`
}

type RegistResponse struct {
	Username         string `json:"username"`
	Nickname         string `json:"nickname"`
	Email            string `json:"email"`
	WalletAddr       string `json:"wallet_addr"`
	UserReferralCode string `json:"user_referral_code"`
	ReferralCode     string `json:"referral_code"`
}

type SeckillRequest struct {
	UserId     int64 `json:"user_id"`
	ActivityId int64 `json:"activity_id"`
	ProductId  int64 `json:"product_id"`
}

type SeckillResponse struct {
	OrderNo string `json:"order_no"`
	Success bool   `json:"success"`
	Msg     string `json:"msg"`
}

type SendEmailRequest struct {
	Email string `json:"email"`
}

type SendEmailResponse struct {
	Success bool `json:"success"`
}

type UpdateUserInfoReqest struct {
	Nickname   string `json:"nickname"`
	WalletAddr string `json:"wallet_addr"`
}
