// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

import (
	"context"

	"google.golang.org/grpc"
)

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token      string `json:"token"`
	UserId     int64  `json:"user_id"`
	Username   string `json:"username"`
	Nickname   string `json:"nickname"`
	WalletAddr string `json:"walletaddr"`
	UserReferralCode string `json:"user_referral_code"`
	ReferralCode     string `json:"referral_code"`
}

type RegistRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
	WalletAddr string `json:"wallet_addr"`
	ReferralCode string `json:"referral_code"`
}

type RegistResponse struct {
	Username       string `json:"username"`
	Nickname       string `json:"nickname"`
	WalletAddr     string `json:"wallet_addr"`
	UserRefferCode string `json:"user_reffer_code"`
	ReferralCode   string `json:"referral_code"`
}


type GetUserRequest struct {
}

type GetUserResponse struct {
	Username       string `json:"username"`
	Nickname       string `json:"nickname"`
	WalletAddr     string `json:"wallet_addr"`
	UserRefferCode string `json:"user_reffer_code"`
	ReferralCode   string `json:"referral_code"`
}

type UserService interface {
	Regist(context.Context, *RegistRequest, ...grpc.CallOption) (*RegistResponse, error)
	Login(context.Context, *LoginRequest, ...grpc.CallOption) (*LoginResponse, error)
	GetUserInfo(context.Context, *GetUserRequest, ...grpc.CallOption) (*GetUserResponse, error)
}