// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	callback "github.com/xxx-newbee/gateway/internal/handler/callback"
	chat "github.com/xxx-newbee/gateway/internal/handler/chat"
	login "github.com/xxx-newbee/gateway/internal/handler/login"
	order "github.com/xxx-newbee/gateway/internal/handler/order"
	pay "github.com/xxx-newbee/gateway/internal/handler/pay"
	user "github.com/xxx-newbee/gateway/internal/handler/user"
	"github.com/xxx-newbee/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestTimer, serverCtx.RateLimiter, serverCtx.Header},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/callbacks/wxpay",
					Handler: callback.PaymentCallbackHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuth, serverCtx.RateLimiter, serverCtx.Header, serverCtx.RequestTimer},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/chat",
					Handler: chat.ChatHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestTimer, serverCtx.RateLimiter, serverCtx.Header},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/captcha",
					Handler: login.GenerateCaptchaHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/chpasswd",
					Handler: login.ChangePasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/email",
					Handler: login.SendEmailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/login",
					Handler: login.LoginHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/register",
					Handler: login.RegisterHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuth, serverCtx.RateLimiter, serverCtx.Header, serverCtx.RequestTimer},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/activity/:id",
					Handler: order.FindActivityHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/activity/create",
					Handler: order.CreateSeckillActivityHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/order/cancel",
					Handler: order.CancelTimeoutOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/order/get",
					Handler: order.GetSeckillOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/orders",
					Handler: order.GetUserSeckillOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/seckill",
					Handler: order.SeckillStockHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/stock/load",
					Handler: order.LoadSeckillStockHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuth, serverCtx.RateLimiter, serverCtx.Header, serverCtx.RequestTimer},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/pay/close",
					Handler: pay.ClosePaymentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/pay/create",
					Handler: pay.CreatePaymentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/pay/query",
					Handler: pay.QueryPaymentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/pay/refund",
					Handler: pay.ProcessRefundHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuth, serverCtx.RateLimiter, serverCtx.Header, serverCtx.RequestTimer},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/deletelog",
					Handler: user.DeleteLoginLogHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/info",
					Handler: user.GetUserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/loginlogs",
					Handler: user.GetLoginLogHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/update",
					Handler: user.UpdateUserInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)
}
